### ISSUE TITLE
Implement game character healths and attributes

### ISSUE THREAD

**Issue by JohnSegerstedt** [JohnSegerstedt/DAT390-ASS3#8]

**Comment by beczipetra89** [comment]
- **Zombie's health**: 

1. takes 10 pea shots to kill a zombie
2. if collides with lawn mover, it instantly kills the zombie, and every other zombies in the same lane

- **Plant's health**: if zombie eats it for 10 seconds, the plant gets destroyed

- **Lawn Mover:** It does not re-spawn, a one time game object that is waiting for a zombie to trigger it. Once it's triggered, it grinds though the entire lane and gets destroyed at the end.
